### ISSUE TITLE
Use of unintroduced terminology "DPoP-Proof JWT or a DPoP-Binding JWT"

### ISSUE THREAD

**Issue by selfissued** [danielfett/draft-dpop#10]
The Token Replay Security Considerations section uses the terminology "DPoP-Proof JWT or a DPoP-Binding JWT".  This came as a surprise at this point in the draft, as these terms weren't adequately previously introduced.

I figured out what you meant by searching back in the draft, but other readers will be likewise surprised.

**Comment by danielfett** [comment]
It is now just called "DPoP token" everywhere.
