### ISSUE TITLE
PAR & DPoP & dpop_jkt 

### ISSUE THREAD

**Issue by bc-pi** [danielfett/draft-dpop#103]
In our discussion on Feb 2 @danielfett said he was going to add some text about PAR and DPoP and binding the authz code. 

I *think* it would be something like saying the client should/must/can/may send DPoP header with the PAR request and the server should/can check that it matches up with the provided dpop_jkt value. But other approaches are also possible - like not needing the explicit dpop_jkt parameter at all because the DPoP header has the info needed to bind to the code.

**Comment by danielfett** [comment]
See PR #111

**Comment by danielfett** [comment]
PR #111 was merged to fix this.
