### ISSUE TITLE
Handling of unknown claims/headers in dpop proof

### ISSUE THREAD

**Issue by jogu** [danielfett/draft-dpop#104]
The current draft says:

> A DPoP proof MAY contain other headers or claims as defined by extension,
> profile, or deployment specific requirements.

(at https://github.com/danielfett/draft-dpop/blob/d2a68a2ba968c15daeadd1b872e45a5cc747bce1/main.md?plain=1#L351 )

There doesn't seem to be any other mention I spotted of how to handle unknown values, and it may be easier to create extensions if this is clear. Is it worth a 'MUST' to say that unknown values must be ignored?

**Comment by bc-pi** [comment]
That text along with the JWT/JWS requirements to ignore unrecognized things seemed sufficient.  

https://datatracker.ietf.org/doc/html/rfc7515#section-4
https://datatracker.ietf.org/doc/html/rfc7519#section-4

**Comment by jogu** [comment]
Ah. I was unaware or had forgotten about those requirements - thank you! I agree, seems sufficient - closing this.
