### ISSUE TITLE
editorial: checking jwk is expected one not mentioned in 'checking dpop proofs'

### ISSUE THREAD

**Issue by jogu** [danielfett/draft-dpop#106]
It seems a little strange to me that:

https://github.com/danielfett/draft-dpop/blob/master/main.md#checking-dpop-proofs-checking

says:

> when presented to a protected resource in conjunction with an access token, ensure that the value of the ath claim equals the hash of the access token that has been presented alongside the DPoP proof.

but then in a completely different section of the document there's:

> [](https://github.com/danielfett/draft-dpop/issues/new#jwk-thumbprint-confirmation-method-jwk-thumb-jwt)Resource servers supporting DPoP MUST ensure that the public key from the DPoP proof matches the public key to which the access token is bound.

It kind of seems like the two requirements are tied together and should be in the same place in the document.

(I sort of worry that a naive developer might use the 'check list' style requirements in "Checking DPoP Proofs" and might entirely miss the need to check the jwk is the expected one.)

**Comment by bc-pi** [comment]
That https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html#name-checking-dpop-proofs is/was supposed to be the validation needed for the DPoP Proof itself in general. While https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html#name-protected-resource-access is about the access token and its binding to the dpop key. When `ath` was added, I suppose it did blur that line a bit. And you are not the first to raise the concern of that important check potentially being missed. So, we can add something at or after that https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html#section-4.3-2.11 step about checking that DPoP proof key matches thekey to which the access token is bound.

**Comment by jogu** [comment]
Sounds good to me, thanks Brian.

>  https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html#section-4.3-2.11 

I'd entirely missed that it's possible to link to particular paragraphs/bullets in specs. I'm not sure whether/how to apply that knowledge in the OIDF conformance test suite...

**Comment by b---c** [comment]
PR #108 has proposed changes

**Comment by b---c** [comment]
df86b20f699b8c75b3ded810b72a703f15802ba9
