### ISSUE TITLE
`ath` presence in non-resource requests

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#112]
Is it an error condition when a stray `ath` claim is present in a DPoP Proof during AS token or [PAR requests](#111)?

This could happen e.g. when native or SPA applications have a single routine for generating DPoP Proofs that always puts `ath` in when it has an existing access token at hand.

**Comment by bc-pi** [comment]
It's clearly incorrect. But should say to reject such a DPoP Proof? Or say to just ignore ath there? Or not say anything specific? I'm not sure.

**Comment by panva** [comment]
Yeah it's clearly incorrect. But does it result in an error on the AS, or does it silently ignore it so long as all other claims `htm`, `htu`, potentially `nonce` are correct plus the `jti` used is unique?

I think there's no harm in ignoring it (not checking it at token/PAR endpoints at all) but wanted to know your opinions, not asking for language to be added.

**Comment by gffletch** [comment]
I'm ok with ignoring the `ath` claim in cases where an access_token is not required to be present as part of the flow.

**Comment by danielfett** [comment]
+1 for ignoring.

**Comment by b---c** [comment]
I'm ok w/ ignoring too.
