### ISSUE TITLE
rename "always_use_dpop" client metadata?

### ISSUE THREAD

**Issue by jogu** [danielfett/draft-dpop#116]
As Daniel and others mention in the conversation around here (and as I had entirely missed when involved in the original discussion about `always_uses_dpod`):

https://github.com/danielfett/draft-dpop/pull/109#issuecomment-1043411324

If the `always_uses_dpop` client meta data sticks at it's current behaviour of affecting only the token endpoint (i.e. doesn't require the use of `dpop_jkt`/'Authorization Code Binding to DPoP Key'), there's an argument to be made for renaming it to avoid future confusion.

Possibly `always_uses_dpop_at_token_endpoint`?

**Comment by panva** [comment]
dpop_bound_access_tokens? Rolls of the tongue and follows the scheme from mtls

**Comment by bc-pi** [comment]
`dpop_bound_access_tokens` was proposed by @panva (I think) but then the comment deleted. Not sure why. I do think that name would work okay/better for the currently defined scope of behavior.

**Comment by jogu** [comment]
If I'm understanding everything correctly (which I may not be), `dpop_bound_access_tokens` would be a change from the current defined behaviour of `always_uses_dpop` - in particular for public clients I believe `always_uses_dpop` means refresh tokens will always be dpop bound.

I'm not entirely confident that I'm aware of the full set of tokens that might be issued from the token endpoint.

**Comment by panva** [comment]
Wouldn't change a thing I think @jogu. The name follows the format of `tls_client_certificate_bound_access_tokens` which also handles refresh tokens for public clients.

**Comment by panva** [comment]
I've removed this suggestion because I anticipated this discussion around refresh tokens and wanted to avoid being pulled into naming things ;) Nevertheless I think it's the name I'd prefer now that @bc-pi re-suggested it :P

**Comment by b---c** [comment]
Sorry @panva :/

**Comment by b---c** [comment]
But yeah, I was also trying to avoid the RT discussion. The RT binding for public clients follows from binding the AT, which in turn means that the dpop header needs to be sent to the token endpoint. So I don't think it needs unique treatment in metadata. Nor do I want to give it unique treatment.

**Comment by panva** [comment]
I'd rather have a convention in place than a hay of parameters that seem to not be related.

**Comment by b---c** [comment]
Somewhat of a loose convention but I tend to agree.

**Comment by b---c** [comment]
PR #120 goes w/ dpop_bound_access_tokens
