### ISSUE TITLE
extract definition of Proof/Binding JWT

### ISSUE THREAD

**Issue by tlodderstedt** [danielfett/draft-dpop#12]
the structure of the JSON payload is the same in all use cases, the only difference lays in the public key carried in the header in case of a binding message. Its definition should be given once (whereas it is now given in Section 3 and 4.

**Comment by tlodderstedt** [comment]
I think one header is sufficient, depending on its intend the client may or may not include a public key, which signals it wants to setup a new binding and overwrite any potentially pre-existing bindings.

It will typically include a public key if it redeems a code for an access tokens, it does not need to add a public key in case of an access token refresh (but it could! and that way rotate its key pair).

**Comment by webhamster** [comment]
In case of access token refresh for public clients, the client needs to provide two JWKs: the proof for the old JWK and the binding for the new JWK. 

Also public clients that want to refresh their tokens must be forced to sign something new and not be able to reuse the DPoP-Binding JWT. Therefore I propose to have two clearly distinguished types of DPoP JWTs.

**Comment by tlodderstedt** [comment]
you are right, we need two headers to differentiate the purpose. 

Note: the dpop proof may also need to contain a public key (e.g. in case of not yet defined asymmetric PKCE)

**Comment by danielfett** [comment]
This has become obsolete; there is only one structure and only one header now (no key rotation any longer).
