### ISSUE TITLE
Requirement for servers to reject DPoP proofs that contain private keys

### ISSUE THREAD

**Issue by jogu** [danielfett/draft-dpop#125]
The current draft says this on the subject of the jwk in the header:

> jwk: representing the public key chosen by the client, in JWK format, as defined in Section 4.1.3 of [@!RFC7515] (REQUIRED). MUST NOT contain the private key.

The "MUST NOT contain the private key" mostly reads like a requirement on the client.

In an quick analysis with a sadly very low number of datapoints, I've so far identified:

1. One AS implementation that does not reject a jwk with a private key
2. One AS implementation that does reject such
3. One client library where sending the private key in the jwk header was easier than sending the public key

So I think there is a potential for some implementors to produce poor quality implementations and private keys to potentially be leaked all over the place (at least for clients not using HSMs/equivalent protected/sandboxes key stores); I think it'd be good to try and block that possibility.

There's currently no explicit "verify the jwk is not a private key" step in the "Checking DPoP Proofs" section. I suggest adding a explicit step that requires this check.

**Comment by b---c** [comment]
The "MUST NOT contain the private key" was intended as a general requirement and is applicable to both roles. Best I can recall, it was added as a reminder to hopefully help prevent exactly the situation you describe. But with that said, adding an explicit step to the "Checking DPoP Proofs" section would be an additional reminder for the server side that will encourage/remind servers to reject such proofs and might very well help protect client implementations from inadvertently sending private keys.  PR #127 adds one short sentence towards that end.

**Comment by b---c** [comment]
done w/ aebac046ec2f52b34a043a996d85b07c9c068930
