### ISSUE TITLE
Reference "confidential client" from oauth2 ?

### ISSUE THREAD

**Issue by ioggstream** [danielfett/draft-dpop#135]
## Question

* Can we reference confidential client from oauth 2.0 or 2.1?

* Can we move from oauth 2.0 to oauth 2.1? It could probably simplify the editing.

**Comment by b---c** [comment]
Referencing/depending on  2.1 is just not realistic here. I'll add "public client" & "confidential client" to the RFC6749 bit of Conventions and Terminology.
