### ISSUE TITLE
Editorial: nonces

### ISSUE THREAD

**Issue by ioggstream** [danielfett/draft-dpop#138]
## Questions on nonce

- see related PR.

**Comment by b---c** [comment]
I see a few PRs with a decent number of changes. Including some nice improvements as well as some things I'm not comfortable with. I'm frankly struggling with the best/easiest/appropriate way to use the given tooling to proceed. I might manually pick and choose pieces to incorporate.

**Comment by b---c** [comment]
I see a few PRs with a decent number of changes. Including some nice improvements as well as some things I'm not comfortable with. I'm frankly struggling with the best/easiest/appropriate way to use the given tooling to proceed. I might manually pick and choose pieces to incorporate.

**Comment by ioggstream** [comment]
@b---c I'm happy to discuss in comments

**Comment by b---c** [comment]
I realize that you'd discuss in comments but that can become terribly time consuming.  I was trying to figure out a reasonable means of incorporating the useful improvements you've made. But you've thrown an awful lot of stuff at this repo. A lot. And some is problematic. And unnecessary. @selfissued has made some comments on the PRs so maybe we're heading down that route. I was honestly trying to avoid that.

**Comment by b---c** [comment]
The many co-authors briefly discussed this offline and decided the best path forward is to cherry-pick the changes from the PRs that are clearly improvements and that do not change the meaning of the text. The contributions and improvements are appreciated (and [recently acknowledged](https://github.com/danielfett/draft-dpop/commit/23f0ab9f0c26a4b4cbab4b893ab548ca31fe4d92)) but we really need to be reasonable and conservative with the changes.

**Comment by ioggstream** [comment]
Comments moved on the PR. For this and the rest, feel free to close issues whenever you think is appropriate :)

**Comment by b---c** [comment]
thx, closing this as I think appropriate :)
