### ISSUE TITLE
Add Error codes

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#14]
(see also errors in RFC6750, extend/copy if necessary)

- dpop-binding JWT is not validating
- dpop-proof JWT is not validating

**Comment by b---c** [comment]
2a695a4fd322632f8d33d3ff29baa1473db49d07 adds 401/WWW-Authenticate challenge for protected resouse access errors and Added invalid_dpop_proof error for DPoP errors in token request added a `invalid_dpop_proof` error for DPoP errors in token requests
