### ISSUE TITLE
Other methods to bound a PK with an AT

### ISSUE THREAD

**Issue by ioggstream** [danielfett/draft-dpop#141]
## Question 

The spec says that

> The authorization server associates the issued access token with the public key from the DPoP proof,
> which can be accomplished as described in (#Confirmation).

No normative language is used here: does it mean that there are there other methods to associate a PK to an AT?
I suggest to condense the normative part in less section so that the readers can easily understand the framework.

**Comment by ioggstream** [comment]
Question 1: 
do the  methods described  in [Section 6.1 - JWK confirmation ](https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-07.html#jwk-thumb-jwt), and in [Section 6.2 - token introspection](https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-07.html#jwk-thumb-intro)
satisfy the "MUST" requirements expressed in https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-07.html#section-6 ?

> Resource servers MUST be able to reliably identify whether an access token is bound using DPoP and ascertain sufficient information about the public key to which the token is bound in order to verify the binding with respect to the presented DPoP proof

Question 2:

Are the confirmation methods above either recommended or mandatory?

**Comment by b---c** [comment]
1: yes 
2: recommended
