### ISSUE TITLE
No normative language in security considerations

### ISSUE THREAD

**Issue by ioggstream** [danielfett/draft-dpop#143]
## I expect

- no normative parts in security considerations
- if they are relevant, should be in the actual specification, and not in the considerations :)

**Comment by b---c** [comment]
But things are messy and normative language often shows up in security considerations. Which, in this draft are referenced from the actual specification text too.  I'll look and see if there's anything that really needs to be pulled out into the actual specification. But frankly not willing to undertake more invasive changes at this point without more compelling reason to do so.

**Comment by ioggstream** [comment]
I understand. To avoid inconsistencies, we could replace normative terms  in the considerations with the correct reference in the specification. This will avoid implementers scattering on the text and ensures consistency.
