### ISSUE TITLE
Considerations on stripping query parameter from requests

### ISSUE THREAD

**Issue by ioggstream** [danielfett/draft-dpop#145]
## Considerations

The `htu` claim contains the request target stripped of the query parameters and the fragment. Since, given the semantic of the HTTP
my understanding is that:

* the query part is relevant for identifying a resource [see http](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.4.2.2.p.5)
 
```
The hierarchical path component and optional query component
identify the target resource within that origin server's namespace
```

* proxy must not modify it

```
A proxy must not modify the "absolute-path" and "query" parts of the received target URI when forwarding 
```

* in some cases, query parameters specify an action (eg. `/foo/user?do=delete`) thus a generic DPoP token issued stripping parameters can actually be broader in scope than expected, when used for generic, machine-to-machine APIs. I would rather leave the decision to strip or not, and the underlying validation to the peers.

**Comment by panva** [comment]
> I would rather leave the decision to strip or not, and the underlying validation to the peers.

That's hardly interoperable between deployments, also not discoverable by any means other than OOB.

**Comment by selfissued** [comment]
I agree with @panva that this would needlessly harm interoperability.

**Comment by b---c** [comment]
I'll add that the nature of the `htu` claim was decided on (w/ WG rough consensus) long long ago and is not really open for relitigation. There are tradeoffs, of course, but simplicity and interoperability were the primary goals.
