### ISSUE TITLE
Talk about extendability of DPoP-JWTs...

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#15]
...if we want that.

**Comment by rfk** [comment]
One possible use of extensibility here would be optional request payload validation, as supported by e.g. the Hawk request-signing scheme:

  https://github.com/hueniverse/hawk#payload-validation

IIUC a similar effect could be achieved here by including a mac of the request payload in the DPrP-JWT.  (Which obviously wouldn't work if you were passing the token itself in the request body, but would be useful in conjunction with https://github.com/danielfett/draft-dpop/issues/18)

**Comment by danielfett** [comment]
Thanks! I added a few sentences explaining that DPoP tokens can be extended by information needed for one's favorite HTTP signing scheme.
