### ISSUE TITLE
Resource servers and new nonce values via 200 OK

### ISSUE THREAD

**Issue by dteleguin** [danielfett/draft-dpop#152]
> Resource servers can also choose to provide a nonce value to be included in DPoP proofs sent to them. They provide the nonce using the DPoP-Nonce header in same way that authorization servers do.

By "in the same way", do we assume resource servers could provide a new nonce via a 200 OK response, similar to authorization servers? If so, would it make sense to mention it explicitly?

**Comment by bc-pi** [comment]
Yes resource servers can provide a new nonce in a 200 response. The "using the DPoP-Nonce header in same way" is trying to say that. I'm not sure, honestly, if it needs to be made more explicit. Some suggested text would be welcome. Though the draft has passed WGLC so the bar on making changes is a little higher now.

**Comment by dteleguin** [comment]
Thanks for the clarifications @bc-pi , please feel free to close
