### ISSUE TITLE
Discuss headers vs. request parameters

### ISSUE THREAD

**Issue by tlodderstedt** [danielfett/draft-dpop#18]
As far as I understand sending credentials im headers is best practice these days. So I'm not sure we need to "cope" with preflight requests by passing the dpop binding and proof as request parameters. 

Let's discuss the implications of headers with respect to CORS/preflight requests.

**Comment by webhamster** [comment]
Parameters:

- No Preflight requests needed
- No settings/header for CORS needed

Headers:
- Right place for credentials
- Preflight requests can be cached
- Preflight might be needed anyway when adding Authorization header

**Comment by tlodderstedt** [comment]
https://developer.mozilla.org/de/docs/Web/HTTP/CORS

**Comment by webhamster** [comment]
Some important requirements for caching a preflight request:

- same method, same origin, same request URL
- server sends appropriate caching headers (some browsers have internal limits, chrome caches only up to 10 minutes)

**Comment by webhamster** [comment]
The following warning is attached to access token usage in URI parameter in RFC6750:

>   Because of the security weaknesses associated with the URI method
>   (see Section 5), including the high likelihood that the URL
>   containing the access token will be logged, it SHOULD NOT be used
>   unless it is impossible to transport the access token in the
>   "Authorization" request header field or the HTTP request entity-body.
>   Resource servers MAY support this method.
>
>   This method is included to document current use; its use is not
>   recommended, due to its security deficiencies (see Section 5) and
>   also because it uses a reserved query parameter name, which is
>   counter to URI namespace best practices, per "Architecture of the
>   World Wide Web, Volume One" [W3C.REC-webarch-20041215].

**Comment by tlodderstedt** [comment]
+1

**Comment by webhamster** [comment]
Pro header: Header with same content will be compressed and not be transmitted repeatedly when using HTTP/2.

**Comment by webhamster** [comment]
For the binding message, a parameter feels more natural (it goes along with code= or refresh_token=). The proof is a credential and should stay in the header.

**Comment by rfk** [comment]
FWIW, +1 to allowing the proof to be passed via header.

I'm interested in this proposal as a potential replacement for some bespoke authorization flows that we do in https://accounts.firefox.com, where we currently use [hawk](https://github.com/hueniverse/hawk#protocol-example) with a shared symmetric signing key.

Would you consider allowing both the access token and the dpop proof as fields in the `Authorization` header? Perhaps along the lines of:

```
Authorization: Bearer+dpop access_token="abc123", dpop_proof="xyz798"
```

From our experience using Hawk on these APIs, keeping all the details in a single header that's already known to contain headers brings some nice simplicity.

**Comment by b---c** [comment]
For Protected Resource access headers should absolutely be the means of transport for whatever DPoP items need to be conveyed. Using HTTP query/form parameters encroaches on the application space of the protected resource, which can result in all kinds of problems. For example, form-encoded body parameters imply that "application/x-www-form-urlencoded" is used in the body (and that there is a body), which rules out JSON in the body. One could use URI query parameters but that adds a lot of leakage vectors. Headers is really where this stuff belongs. Trying to optimize out of CORS preflights is a fools errand that will not end well.

**Comment by dwaite** [comment]
I would suggest whatever we do aligns with RFC 4950, which provides for the access token to be sent as a:
1. query parameter
2. form encoded body (but oddly not part of a multipart form)
3. header (specifically the authorization header)

In the header case, the question becomes whether to send the proof, and key material:
1. outside the authorization header as separate headers, to provide transparent fallback for old applications
2. as a new dpop-specific authorization header type (with the assumption applications which do not support dpop will reply with www-authenticate: bearer to indicate so

**Comment by b---c** [comment]
Aligning with ICMP Extensions for Multiprotocol Label Switching seems difficult but if you think it's necessary... ;) 

Really though, I don't think the reasons that the query and form options ended up in [RFC 6750](https://tools.ietf.org/html/rfc6750) are compelling and the practice/allowance probably shouldn't be continued.

**Comment by tlodderstedt** [comment]
+1

**Comment by b---c** [comment]
The question about where to send the proof and key material within header(s) is worth consideration/discussion however I think.

**Comment by danielfett** [comment]
A single `DPoP` header it is.
