### ISSUE TITLE
Possible token exfiltration consideration

### ISSUE THREAD

**Issue by dwaite** [danielfett/draft-dpop#25]
I believe there are three attack vectors due to logic injection in public clients: [1](#1)

1. the inspection and possible exfiltration of unprotected state
2. the augmentation/modification of behavior
3. the inspection and modification of traffic

Under mTLS and token binding, you can still view and modify state, behavior, and traffic - but we assume you can't exfiltrate the tokens because you can't capture and recreate the TLS setup.

For these however, if the client private key or TLS implementation can be modified as part of the application, the crypto information can be exfiltrated along with the tokens.

With DPoP in a browser, I can put the key into WebCrypto which will cause the platform to manage it as non-exportable, but if an attacker managed to get a service worker installed they can potentially view and modify the communication with the AS. They could alter the proof token to bind to their own exportable key, and even modify the headers on other requests in an attempt to disguise that the key and tokens had been exfiltrated.

<small><b id='1'>[1]</b>: <i>Native apps can have issues due to bundled malicious code and dynamic library/code loading, such as remote update frameworks and advertising libraries. But Javascript rightfully has a reputation since preventing arbitrary code execution is manual or opt-in.</i></small>

**Comment by dwaite** [comment]
Since the browser is presumably able to protect some of its behavior from malicious code, it might be possible to mitigate the effect of some of the attack if the client could verify the JWT included a reference to the intended bound token. This would need to be tied to a static representation of the key, since the assumption is any metadata lookup could be modified.

But preventing this kind of attack in-flight is probably better spent recommending mitigations - not allowing user or dynamic content to be served as a javascript mime type on the origin server, having the origin server for the application understand and act on the Service-Worker header, and using CSP.

**Comment by danielfett** [comment]
@dwaite Could you please add your considerations to the Security Considerations section? I think 3 is covered already.

**Comment by danielfett** [comment]
@dwaite Could you please prepare a pull request for this?

**Comment by selfissued** [comment]
@dwaite, do you still plan to write this PR or should we close this issue?

**Comment by dwaite** [comment]
This would be a consideration, I'll time-box this by the 8th to propose text or close.

**Comment by dwaite** [comment]
closing.
