### ISSUE TITLE
AS metadata, client metadata

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#27]
I’m thinking the OP should expose metadata about the supported signing algorithms. 

A dynamically registered client might also announce the algorithm it intends to use. 

This is parallel to token_endpoint_signing_alg client metadata and token_endpoint_auth_signing_alg_values_supported AS metadata.

**Comment by panva** [comment]
Suggestion:

New section (under section 4 - DPoP Proof JWT?)

```
Authorization Server Metadata

   This document introduces the following new authorization server metadata [RFC8414] parameter to signal the JWS "alg" values the authorization server supports for DPoP proof JWTs:

   dpop_signing_alg_values_supported
      OPTIONAL.  JSON array containing a list of the JWS "alg" values supported by the authorization server for the DPoP proof JWT
```

In IANA Considerations
```
Authorization Server Metadata Registration

   Per this specification, the following values have been registered in the IANA "OAuth Authorization Server Metadata" registry [IANA.OAuth.Parameters] established by [RFC8414].

   Metadata Name:  "dpop_signing_alg_values_supported"
   Metadata Description:  JSON array containing a list of the JWS "alg" values supported by the authorization server's for the DPoP proof JWT
   Change Controller:  IESG
   Specification Document(s):  Section x.x of [[ this specification ]]
```

I'm not proposing client metadata as I have yet to find a good reason for it.

**Comment by panva** [comment]
@b---c ☝️

**Comment by b---c** [comment]
Thank you @panva !

**Comment by b---c** [comment]
Note to self, this text might need to be revisited when adding AS metadata:

> A client typically cannot know whether a certain AS supports DPoP. It
therefore SHOULD use the value of the `token_type` parameter returned
from the AS to determine support for DPoP: If the token type returned
is `Bearer` or another value, the AS does not support DPoP. If it is
`DPoP`, DPoP is supported. Only then, the client needs to send
the `DPoP` header in subsequent requests and use the token type
`DPoP` in the `Authorization` header as described below.

**Comment by panva** [comment]
I find that new text not covering the case i talked about on the list. Only the RT being bound. The token type will stay bearer but an AS needs to get the dpop header in subsequent refresh token exchanges. 

Also issuing dpop tokens only for some audiences/scopes that could be specified at refresh token request time.

**Comment by b---c** [comment]
Added dpop_signing_alg_values_supported authorization server metadata with db6bac73b8c3ae4e2ab292db7f0de75deee380e6
