### ISSUE TITLE
example EC JWK not fully to RFC 7518

### ISSUE THREAD

**Issue by b---c** [danielfett/draft-dpop#30]
Per https://tools.ietf.org/html/rfc7518#section-6.2 the 'octet string MUST be the full size of a coordinate for the curve specified in the "crv" parameter' for x and y but the examples in -00/01 have a "y" that is too short to be full sized for P-256. It's unusually short compared to anything that I've seen before - I'm curious, where'd this key come from? https://tools.ietf.org/html/rfc7517#section-3 has an example showing the x and y the same length. 

Also the use of "kid" seems a bit out of place in the given context. Is there some reason for it?

**Comment by danielfett** [comment]
Not sure where I copied that from for the first draft. I took the key from 7515 now and removed `kid` (for now, let's see if we want to externalize the keys again).
