### ISSUE TITLE
contradictory recommendations on reuse vs. replay prevention of proof JWT 

### ISSUE THREAD

**Issue by b---c** [danielfett/draft-dpop#31]
[Section 5](https://tools.ietf.org/html/draft-fett-oauth-dpop-01#section-5) has this recommendation that clients reuse the same proof JWT. 
```
   It is RECOMMENDED that clients reuse the same JWT if possible to
   improve the performance of the client, the data transfer (caching),
   and the authorization server.
```

However there are several places (listed below) where the recommendation is for the server to track `jti` values of proof JWTs to prevent replay. The recommendations seem problematic, if both client and server followed them. 

https://tools.ietf.org/html/draft-fett-oauth-dpop-01#section-4
```
 o  "jti": Unique identifier for this JWT chosen freshly when creating
      the JWT (REQUIRED).  SHOULD be used by the AS for replay detection
      and prevention.  See Security Considerations [1].
```

https://tools.ietf.org/html/draft-fett-oauth-dpop-01#section-5
```
   8.  if replay protection is desired, that a JWT with the same "jti"
       value has not been received previously.
```

https://tools.ietf.org/html/draft-fett-oauth-dpop-01#section-6
```
   9.  if replay protection is desired, that a JWT with the same "jti"
       value has not been received previously.
```

https://tools.ietf.org/html/draft-fett-oauth-dpop-01#section-11.2
```
   Furthermore, the "jti" claim in
   each JWT MUST contain a unique (incrementing or randomly chosen)
   value, as proposed in [RFC7253].  Resource servers SHOULD store
   values at least for the lifetime of the respective JWT and decline
   HTTP requests by clients if a "jti" value has been seen before.
```

**Comment by panva** [comment]
The first one is possibly meant to be a JWK instead of JWT?

**Comment by danielfett** [comment]
No, Brian is correct, that are contradictory statements. I think that the recommendation should be to reuse JWTs **if no replay detection is applied**.

**Comment by b---c** [comment]
> I think that the recommendation should be to reuse JWTs if no replay detection is applied.

But the client has no (good) way of determining if replay detection is being applied on the server side.

**Comment by tlodderstedt** [comment]
I agree with Brian’s comment. We include the jti to allow the recipient to detect per message reply bur the client cannot determine whether replay detection is actually in place. My feeling therefore is we should not recommend reuse of the proof JWT at all.

**Comment by b---c** [comment]
Yeah, I think it's really one or the other but not both.

**Comment by danielfett** [comment]
I removed the recommendation for reuse.
