### ISSUE TITLE
passing of dpop in resource request. 

### ISSUE THREAD

**Issue by mengan** [danielfett/draft-dpop#33]
Good afternoon,     using this first comment to join the group and threads. 

I believe the draft should be updated to capture a sample request to a resource server. Such that we can see the presence of the extra header. 

Authorization: Bearer <jwt>
xxxxx: <dpop> 

Note:  T-Mobile has a practice with "x-authorization" containing the pop token generated by the client.

**Comment by danielfett** [comment]
Thanks, I added an example.
