### ISSUE TITLE
Underspecified statement about "token_type"

### ISSUE THREAD

**Issue by selfissued** [danielfett/draft-dpop#36]
The last sentence of Section 5 says "The client MAY use the value of the "token_type" parameter to determine whether the server supports the mechanisms specified in this document."  This seems underspecified to me.  How does the client use this and under what circumstances would it do this?

**Comment by danielfett** [comment]
Updated guidance: 

> A client typically cannot know whether a certain AS supports DPoP. It
therefore SHOULD use the value of the `token_type` parameter returned
from the AS to determine support for DPoP: If the token type returned
is `Bearer` or another value, the AS does not support DPoP. If it is
`Bearer-DPoP`, DPoP is supported. Only then, the client needs to send
the `DPoP` header in subsequent requests and use the token type
`Bearer-DPoP` in the `Authorization` header as described below.
