### ISSUE TITLE
referal-binding

### ISSUE THREAD

**Issue by mengan** [danielfett/draft-dpop#39]
should we support referal binding flows? 

with the dpop process we want individual client instances to generate and use their own key pair. but the client instance may still be using a client server to supply client secrets in the Code flow. If the client secret has been added then the dpop may be invalid. (destination url...
). 

ie...   

client . ----> client_server --->token endpoint

should we enable the client_server to make the token request, but then make a referered binding so the access_token issued is issued to the client's key instead of the dpop the client server is capable of making. 

ie... 
client server supplies

{
"iss":"clientid",
"iat":1552875882,
https_uri:"resource path"
referred_binding
}

**Comment by mengan** [comment]
Alternative is the conversation today that the initial Token request could get away without requiring the dpop, and instead just a clear unsigned statment of the Key the token should be issued to.

**Comment by tlodderstedt** [comment]
If there is a (client) server is involved, I would rather implement the resource server access in that backend and go with mTLS for authn & sender constraining

**Comment by mengan** [comment]
so we have found that an increasing number of applications are pushing the computational efforts from their servers down to the client instances. (It free for an app to execute calls and render information on a phone, vs the developer having to pay for AWS resources to do it all server side.  Under this paradygm clients are looking for the ability to have the Tokens issued to their client instances so the client instances can make the resource requests.   But as you know we don't want client instances to hold secrets. (client secret, or the Clients Registered private/public key set).   so the ability for a client server to pass in a refered binding for the client is an ability that should be supported.  (Possibly by forcing the client to make the dpop, that then gets sent from client instance to the client server, and then into the token endpoint. (I would prefer a referred-binding thought)

**Comment by selfissued** [comment]
This seems unnecessary.  I propose that we close this issue on this basis.

**Comment by b---c** [comment]
This years old issue and would be pretty divergent from WG (rough) consensus on the fundamentals of the protocol. Closing as such.
