### ISSUE TITLE
Do we need DPoP key rotation?

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#40]
Key rotation would enable a client, when using a refresh token, to provide a new DPoP key.

I can come up with two situations where this *might* be useful:

1. A client just wants to follow good crypto practices and rotate the DPoP key in regular intervals. I do not, however, see situations where the client's DPoP key would be compromised and the client would not be royally screwed anyway. Not sure if this is actually needed therefore.
2. The DPoP key used by a client is contained in an external JWKS (e.g., referred to by client metadata `jwks_uri`). The keys in this JWKS are rotated in regular intervals and the client does not want to make an exception for the DPoP key. In that case, the clients needs to rotate the DPoP key as well.

Both are not really strong cases. Any other thoughts on this?

**Comment by dwaite** [comment]
Just verifying - in the second case (key is in client metadata), would this mean that the new key is potentially required after refresh without any explicit client action during refresh?

**Comment by danielfett** [comment]
> Just verifying - in the second case (key is in client metadata), would this mean that the new key is potentially required after refresh without any explicit client action during refresh?

Since the client would refer to one explicit key during the initial token request, the key would not be automatically rotated without the client asking for that. At least that is the current model.

**Comment by b---c** [comment]
I'd argue that refresh tokens only be bound to a DPoP key when issued to public clients (similar to MTLS https://tools.ietf.org/html/draft-ietf-oauth-mtls-14#section-4). 

With so called confidential clients that have authentication credentials, a refresh token is already indirectly bound to those credentials through the client (discussed in MTLS https://tools.ietf.org/html/draft-ietf-oauth-mtls-14#section-7.1).  And such clients could freely rotate their dpop keys when getting new access tokens. Or not. It's up to them. But it's possible. 

So I think the question is more narrow than 'Do we need DPoP key rotation?' and is more "do we need to support DPoP key rotation for refresh tokens and public clients?"

**Comment by mengan** [comment]
Daniel we discussed this in CA. 

I am a big fan of clients using bindings, but if a client is capable of od preforming dpop signatures, then I believe the clients should be using client assertions instead of client secrets with their token requests.    in which case the currently registered client key can be used to sign the new dpop+jwk. (see the referred binding thread). 

so this seems like a lot of effort to get implicit flow clients the ability to do refresh tokens that are dpop signed, the ability to rotate...

**Comment by danielfett** [comment]
In a first step, I removed the distinction between proof and binding now.
