### ISSUE TITLE
access token and dpop containing a redundant CNF

### ISSUE THREAD

**Issue by mengan** [danielfett/draft-dpop#42]
Apology if this was covered in a previous discussion. 

I notice that the current md draft has a CNF in the at+jwt (good) and in the dpop+jwt (redundant?)   If the Dpop is provided in the Token request then i can understand why the cnf might be added to the request. but for the more numerous resource requests I work that a lazy developer may take the CNF from the dpop to validate the same dpop defeating the entire binding.

**Comment by danielfett** [comment]
Please see the discussion in Issue #26. I hope that we can address the potential security issue when developers skip checking of the relationship between the AT and DPoP token by two (a) simplification of the overall protocol and (b) a clear, pseudocode-like description of the algorithm for checking DPoP tokens.
