### ISSUE TITLE
Recommend mTLS if possible

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#44]
Should we be more explicit about recommending to implement mTLS instead of DPoP if that suits the use case?

**Comment by panva** [comment]
Use-case isn’t the only thing driving this. 

For instance dynamic registration or Mobile Device Management (for per installation keys and cert) is a prerequisite for mtls to be used “right”, DPoP doesn’t have that restriction.

**Comment by tlodderstedt** [comment]
Can you please elaborate? I don’t see a need for those prerequisites. Native apps can use self-signed certs and public clients.

**Comment by panva** [comment]
Ah nevermind :facepalm: I was thinking of mtls with client auth, not mtls only for sender constraining.

**Comment by tlodderstedt** [comment]
That’s tricky for native clients ;-) I think the only way is to move the OAuth logic to a backend and make it a confidential client.

**Comment by danielfett** [comment]
Pull Request #54 addresses this. Opinions on the wording?

**Comment by b---c** [comment]
I had one minor comment on Pull Request #54 but otherwise think it's fine.

**Comment by danielfett** [comment]
Thanks, this PR was merged. Closing this issue.
