### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by b---c** [danielfett/draft-dpop#48]
Pretty sure this https://tools.ietf.org/html/draft-fett-oauth-dpop-02#section-11.3 isn't what was intended.

**Comment by b---c** [comment]
closed with no change?

**Comment by danielfett** [comment]
Should be fixed. The change is committed, but not pushed yet. 

Am 16. Juli 2019 18:07:47 MESZ schrieb Brian Campbell <notifications@github.com>:
>closed with no change? 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/danielfett/draft-dpop/issues/48#issuecomment-511882078

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by b---c** [comment]
For other folks following along at home, it would super helpful to push and and include a link to the commit that has the fix for an issue in the comment on the comment that closes or resolves it.

**Comment by danielfett** [comment]
Github creates the link automatically when something is pushed. There you go.

**Comment by b---c** [comment]
thx, hadn't been seeing that
