### ISSUE TITLE
http_uri syntax underspecified

### ISSUE THREAD

**Issue by selfissued** [danielfett/draft-dpop#5]
The draft currently defines `http_uri` as "The HTTP URI used for the request (REQUIRED)."  We should probably say whether there are restrictions on whether a fragment may be included, whether the URI must use the "https" scheme, whether query parameters may be included, etc.

Also, I think that "HTTP URI" should be changed to simply "URI".

**Comment by danielfett** [comment]
Updated wording: 
> The HTTP URI used for the request, without query and
   fragment parts (REQUIRED)
> ...
> Servers SHOULD employ Syntax-Based Normalization and Scheme-Based
Normalization in accordance with Section 6.2.2. and Section 6.2.3. of
[@!RFC3986] before comparing the `http_uri` claim.
