### ISSUE TITLE
consider a baseline MUST support algorithm

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#61]
From Secdir last call review of draft-ietf-oauth-access-token-jwt-11

> 2.  (Issue) The specification does not specify any mandatory to implement for
the recommended asymmetric algorithms.  This will not help interop.  Perhaps
specify one or both of  "RS256" and "ES256".

Should we avoid such review item for DPoP and specify a required-to-support JWS Algorithm Identifier early?

**Comment by bc-pi** [comment]
I don't personally love including mandatory-to-implement alg(s) and I think we can probably avoid specifying one here. 

There's the AS `dpop_signing_alg_values_supported` metadata https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-02.html#section-5.1 and the `algs` challenge parameter https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-02.html#section-7.1-9.6 

That kind of discovery or negotiation is usually enough to ward off that kind of secdir comment. 

So I guess I'd prefer to leave it as-is for the time being. And add an MTI (ES256 seems the logical choice) later only if it becomes a sticking point in IESG reviews.

**Comment by panva** [comment]
That sounds good to me!
