### ISSUE TITLE
Downgrade from RFC 8705 (MTLS) to DPoP?

### ISSUE THREAD

**Issue by will-bartlett** [danielfett/draft-dpop#63]
The current text prevents a downgrade attack to Bearer:

>    Protected resources simultaneously supporting both the "DPoP" and
>   "Bearer" schemes need to update how evaluation of bearer tokens is
>   performed to prevent downgraded usage of a DPoP-bound access tokens.
>   Specifically, such a protected resource MUST reject an access token
>   received as a bearer token per [!@RFC6750], if that token is
>   determined to be DPoP-bound.

However, it doesn't mention downgrade attacks from one PoP mechanism to another. 

The spec seems to imply that a DPoP token is indicated by the presence of the "cnf" claim. Then, DPoP-aware resources should reject tokens with a "cnf" claim without a DPoP Proof. However, the same logic seems to apply to RFC 8705 - an MTLS-aware resource should reject tokens with a "cnf" claim without MTLS transport. Consider then a resource which supports both DPoP and MTLS (or another PoP mechanism) - how does the resource know which PoP mechanism is intended by the client if all PoP mechanisms are indicated by the same "cnf" claim? Given that different PoP methods have different security characteristics, doesn't the ambiguity around the "cnf" enable downgrade attacks?

Or, is the intention that the confirmation method indicates the type of PoP required? (jkt => DPoP, x5t#S256 => MTLS, etc)

**Comment by b---c** [comment]
The confirmation method does indicate the type of confirmation needed so I don't see the ambiguity.

**Comment by will-bartlett** [comment]
> The confirmation method does indicate the type of confirmation needed 

That's good to hear.

> so I don't see the ambiguity.

I can't quite find your statement in the spec. The spec seems to say that the DPoP confirmation method SHOULD (but not MUST) be in the "jtk" confirmation method.

> the public key information SHOULD be represented using the jkt confirmation method member defined herein

but it doesn't quite say the reverse - that "jtk" is used _only_ used for DPoP.

**Comment by jricher** [comment]
I can see the point here -- in addition to the key itself, maybe the token structure and introspection response should also contain the presentation method? There's already the "token_type" field in introspection that would work for DPoP in that case, but there isn't a version of that for JWT.

**Comment by bc-pi** [comment]
The representation of the key or certificate to which the access token is bound in RFC 8705 or the DPoP draft was intentionally left a bit loose with the hope that enough structure was given to facilitate interop between independent ASs and RSs using JWT or introspection but still allow for the deployments where the AS and RS are using a shared DB or whatever, which OAuth has always made room for. And cnf methods have typically been somewhat generic so I was mostly just following that pattern. Perhaps there's some tightening up or clarification that can be done in this respect? To DPoP anyway - RFCs don't change once they become RFCs. I don't know if that would actually address the concern of this issue though. 

And practically speaking I'm still not seeing how the actual concern would play out. To downgrade from MTLS to DPoP would mean that an RS would have to accept an access token with the hash of a cert as the confirmation and somehow decide that that cert hash acceptably corresponds to the public key in the DPoP proof? Maybe I'm just too dense but I don't see it. And while different PoP methods do have somewhat different security characteristics, is one clearly outright better or worse than another? I dunno.

**Comment by will-bartlett** [comment]
It's all just crypto malleability. If you can persuade a client to construct a request that could be either of one of two methods, you permit downgrade between the two of them. It's not clear to me that in practice you can convince a client to construct such a request for MTLS and DPoP, but if the industry continues to accumulate standards like DPoP and SHR, all of which have "sign the JWT" type semantics, eventually some of them will overlap.

> And while different PoP methods do have somewhat different security characteristics, is one clearly outright better or worse than another? I dunno.

I think so. The basic "does this protect the query/body parameters?" question - DPoP doesn't, MTLS and SHR do. If you could downgrade from one that does protect these parameters to one that does not, then you can start using a refresh token to request access tokens with different scopes, etc.

**Comment by danielfett** [comment]
If I see this correctly, the main point here is that the presence of `jkt` in `cnf` currently says: "This is the key (fingerprint) to check against.", while the requirement for a DPoP proof signed by that key is implicitly given by this specification. And I think that this is a valid point and it makes sense to make the "dpop" requirement more explicit, just as we did in the `typ` of the JWT (and for the same reasons). We could rename `jkt` to `dpop+jkt` or similar, or add something like `token_type`.

Re
> the public key information SHOULD be represented using the jkt confirmation method

It is important to note that we also have 

> Resource servers MUST be able to reliably identify whether an access token is bound using DPoP

a few sentences before that, so we should be fine here.

**Comment by selfissued** [comment]
I don't see an actual problem here, as pointed out in the discussion above.  I propose that we close this issue on this basis.

**Comment by will-bartlett** [comment]
I'm fine with closing. 

>> Resource servers MUST be able to reliably identify whether an access token is bound using DPoP

This is sufficient.
