### ISSUE TITLE
Additional requirements for JWK in DPoP Proof JWT

### ISSUE THREAD

**Issue by adeinega** [danielfett/draft-dpop#65]
I suggest rejecting a DPoP proof when the `jwk` parameter contains either

1. the private key (yes, it's possible per https://tools.ietf.org/html/rfc7517)
2. the keys provided/references by the `x5u` (X.509 URL) and `jku` (JWK Set URL)

as a protection against misuse.

**Comment by panva** [comment]
https://tools.ietf.org/html/rfc7515#section-4.1.3

The JWS jwk header parameter definition explicitly says it carries a public key in a JWK format.

**Comment by bc-pi** [comment]
Yeah, I'd assumed the definition of the `jwk` header from RFC 7515 (which is referenced from dpop https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-02.html#section-4.2-2.3) would be good enough to convey that the `jwk` header is the public key. Maybe we could add little note/reminder that the private key mustn't ever be included.

**Comment by b---c** [comment]
090c99b36ee69348ec95d0a6ef1e37ecc279b1f5

**Comment by adeinega** [comment]
@b---c, what do you think about the second point?

**Comment by bc-pi** [comment]
`jku` isn't even defined for JWK. 

And there may well be legitimate reasons to have `x5u` - see for example, https://bitbucket.org/openid/fapi/src/master/Financial_API_Simple_HTTP_Message_Integrity_Protocol.md#markdown-header-63-x5u-certificate-url

**Comment by adeinega** [comment]
Got it, thanks. https://bitbucket.org/openid/fapi/src/master/Financial_API_Simple_HTTP_Message_Integrity_Protocol.md talks also about `jwks_uri` and among other things state that

`For the purposes of non-repudiation the receiver of a DPoP proof must determine that the key the sender used to sign the proof is valid for that purpose. This is beyond the scope of this specification as it is likely to be ecosystem and implementation specific. Here are some examples of how such verification could be achieved.`

which leaves a lot of wiggle room to mix the public key with other parameters such as `x5u`, `x5c`, and so on. Although, it's a different story.
