### ISSUE TITLE
Tie keys back to the authorization endpoint for E2E PoP protection

### ISSUE THREAD

**Issue by will-bartlett** [danielfett/draft-dpop#71]
Some identity providers already provide some proof of possession (PoP) protection on the authorization endpoint. For example, an identity provider might require that the user communicate with the authorization endpoint over MTLS, or an identity provider might require that the user use a credential that proves PoP, like a FIDO key.

In such a situation, it is highly advantageous to tie the binding used on the token endpoint (DPoP) to the binding used on the authorization endpoint. Such binding mitigates MITM attacks or disconnect-and-log attacks where an attacker attempts to redeem the authorization code with an attacker supplied proof. This binding removes the requirement for authorization codes to be truly one time use (which is still not uniform across the OAuth ecosystem) - this is critical to the security of DPoP. If http requests are actively being logged (e.g. by a corporate proxy, web browser, and STS infrastructure) and an attacker can access one of these logs at a time when the authorization code is still useable, the attacker can re-redeem the authorization code and supply their own DPoP binding.

One way to tie the DPoP keys back to the authorization endpoint is using an RFC 7638 JWK thumbprint. If the JWK thumbprint of the DPoP binding key was sent to the authorization endpoint in a new parameter (e.g. `dpop_jwk_thumb") , this thumbprint would be sent over the STS's authorization endpoint binding (e.g. MTLS), and the the authorization server could require that the DPoP keys used on the token endpoint have a matching thumbprint. Such a binding connects authorization PoP to token PoP and allows E2E protection.

**Comment by will-bartlett** [comment]
Overlap with #70

**Comment by selfissued** [comment]
This was addressed by PR #89 .
