### ISSUE TITLE
Editorial comment: Section 3

### ISSUE THREAD

**Issue by PieterKas** [danielfett/draft-dpop#75]
The following statement does not capture that the DPoP proof may also include the hash of the Access Token (‘ath’): “Roughly speaking, a DPoP proof is a signature over a timestamp and some data of the HTTP request to which it is attached.”. Is it possible to add language to make is clear that the hash of the Access Token is included when presenting to the Relying Party? For example: “A DPOP proof is presented when requesting a token from an Authorization Server and when presenting a token to a Relying Party. Roughly speaking, a DPoP proof for requesting a token from an Authorization Server is a signature over a timestamp and some data of the HTTP request to which it is attached. A DPoP proof for presenting a token is a signature over a timestamp, some data of the HTTP request to which it is attached and a hash of the token.

**Comment by bc-pi** [comment]
243258a0 has some new text roughly along those lines
