### ISSUE TITLE
Editoria Comment Section 7.1 (Figure 15)

### ISSUE THREAD

**Issue by PieterKas** [danielfett/draft-dpop#79]
The example shows the response in case of an invalid DPoP proof. Should the error returned be “invalid_dpop_proof” instead of “invalid_token”?

**Comment by bc-pi** [comment]
That example at https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-03.html#section-7.1-13 says the response is a case of  failed "confirmation of the DPoP binding in the access token" and “invalid_token” is what I'd expect in that case. 

Also “invalid_dpop_proof” isn't currently a defined error code for WWW-Authenticate header from RSs.  Although there has been discussion about making it one: https://mailarchive.ietf.org/arch/msg/oauth/Ftvo-7JEXYqnsR4LvDEQLMSSTKg/
