### ISSUE TITLE
Describe and prevent double-code-usage attack

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#85]
See https://mailarchive.ietf.org/arch/msg/oauth/9XNtD-VWmCGwM1QLAp8idt6yW1o/

**Comment by selfissued** [comment]
I believe it would be reasonable to describe the double-code-use attack and how `dpop_jkt` parameter usage (see PR #89) prevents it.

**Comment by danielfett** [comment]
"If there can be more than one successful token request, all it takes is code_challenge and the code sitting around somewhere in accessible memory and an XSS attacker can exfiltrate them and use them on his own device, binding the resulting token to an attacker-controlled key."

Should be solved with PR #89

**Comment by danielfett** [comment]
The attack should be mentioned, nonetheless.
