### ISSUE TITLE
Known limitation, or unintended consequence?

### ISSUE THREAD

**Issue by sbweeden** [danielfett/draft-dpop#87]
Consider a public client communicating with an AS using DPoP.

When an initial grant (e.g.  azn code with PKCE) is received at the client, DPoP is used as part of the exchange of the code for initial refresh token (RT) and access token (AT).

The AS policy requires sender-constrained access tokens and so returns the DPoP token_type.

Because the RT MUST also be sender-constrained (per section 5), this means that the public key associated with all RT's and all AT's, for the life of the grant (i.e. across all refresh_token flows), must remain bound to the same initial DPoP public key.

In the case of confidential clients issuing sender-constrained AT's with DPoP, the RT is not sender-constrained, and therefore the client can choose to use a new DPoP keypair per refresh token flow (i.e. each AT could be bound to a unique DPoP keypair).

Is it an intended consequence of this spec that public clients using sender-constrained AT's must use the same DPoP keypair for all AT's whereas that is not a requirement for confidential clients?

Is there really a good use case for using per-AT DPoP keypairs vs the same DPoP keypair for the lifetime of the grant?

**Comment by bc-pi** [comment]
It's a known consequence that was intentional with the aim of getting the benefit of DPoP bound RTs for public clients but not introducing the complexity of a mechanism for update or rotation of the DPoP key or mulitiple proofs in a request. There's always tradeoffs. This seemed like the right  tradeoff in terms of functionality and complexity.

**Comment by sbweeden** [comment]
No problem - I'll close the issue.
