### ISSUE TITLE
lacks server-contributed nonce guidance

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#88]
_Following up as per the last WG Interim on DPoP._

I struggle in imagining or prototyping an implementation where the enforcement (or even general use) of server-contributed nonces is efficient for both the server as well as the client, i.e. does not require extensive tracking of current and next nonces for each individual "session" - whatever that may be in this context.

I can imagine the AS could utilize a time-based counter, have a secret and similar to TOTP just accept a window of nonces based on an hmac for which the key is kept a secret. The downside being that a client will be required to POST to the token endpoint twice before it gets the access/refresh token. It may then pause messaging for a bit and once resumed again required to POST twice the refresh token grant to get a fresh access token. Similarly on the RS side of things. Also every actor at a given time would have the same nonce as to prevent having to compute them for every request based on something unique to it, e.g. the client or AT value. Is that a problem in itself? I imagine not given the point is to limit the lifetime of the proofs to prevent use of pre-calculated proofs.

1) To avoid having to track state with every actor and have 100% synchronised clocks on the AS, is it okay for an AS to have a number of nonces accepted at any given time? Similar to how TOTP works.
2) Can we recommended an approach that is efficient and does not require frequent re-trying of protocol messages on the AS and RS?
3) What is the client-software expected behaviour? Use the last nonce presented to it regardless of the end-user session? A dumb implementation can just always request without nonce, get the header, repeat with a nonce. But that's really inefficient. The behaviour should be defined for client software as well as for the AS such that client software can be developed that works universally and efficiently.

**Comment by bc-pi** [comment]
Hope/plan to discuss at OSW6...

**Comment by bc-pi** [comment]
As mentioned in #92 I'd like to get to something in the draft that's simple and efficient and implies implementations which are the same. Like where the client can just use the last nonce received per host and things will work (most of the time at least). I'm not sure how to get there though. But maybe I'm making it harder than it needs to be. Thoughts/suggestions welcome.

**Comment by selfissued** [comment]
I agree that the intent is that the client only keeps one once - the last one received.  This is simple and works, provided messages don't arrive out-of-order.  And the good news, is that using the wrong nonce is a self-correcting situation.  The server responds with a new one and the client retries, after which all is good.  I'm fine saying that in the draft.

As @bc-pi points out - no reason to make this appear to be harder than it needs to be.

**Comment by bc-pi** [comment]
There might be concurrent messages though and there's no direct correlation of the next request sent after receiving a response. Which makes text like "If the nonce claim in the DPoP proof of a token request does not exactly match the nonce supplied by the authorization server to the client, the authorization server MUST reject the request" potentially problematic.
