### ISSUE TITLE
expected error when nonce is stale

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#91]
Assume a client has a `DPoP-Nonce` from previous interactions with an AS(or RS) but the nonce value has since became stale.

When the next request is made, the AS/RS validates the used nonce and rejects the DPoP Proof on the account of the nonce being stale.

Question is: What is the error? `use_dpop_nonce` or `invalid_dpop_proof`?

The current language does not clarify this condition and so both can potentially be used. The issue is that `invalid_dpop_proof` can also be thrown for many other reasons (jti re-use, iat clock skew, etc) and so it may be turn out useless to retry a request when `invalid_dpop_proof` was returned. 

Should we make it a normative requirement to use `use_dpop_nonce` for both when nonce is missing from the proof as well as when it's provided but no longer valid?

**Comment by bc-pi** [comment]
Yeah, I think `use_dpop_nonce` with a `DPoP-Nonce` would be the appropriate response in that situation for the reasons you mention.

**Comment by selfissued** [comment]
I agree with @bc-pi.  I can create a PR adding that to the normative text.
