### ISSUE TITLE
invalid_dpop_proof and use_dpop_nonce http status response codes

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#93]
These two new error codes are defined for both token error response and resource error response.

I believe when returned by the token endpoint the intended HTTP Status code is 400.

I believe this is likewise the intention for resource error response, correct? 

~If that's the case then `Figure 15` example should be updated for two reasons~

~1) to actually use `invalid_dpop_proof`, it now uses `invalid_token` (#94)~
~2) to be a 400, not a 401~

Likewise `Figure 20` to use 400, not 401.

If it is intended for token responses to be 400 but resource error responses to be 401 that's okay too, nevertheless going through an implementation in an OIDC server this subject confused me since this server has both the token endpoint as well as a protected resource (userinfo endpoint) and so they re-use errors and their status codes.

**Comment by bc-pi** [comment]
It is intended for token responses to be 400 but resource error responses to be 401. 

A 401 has to (and can) have a www-authenticate header https://datatracker.ietf.org/doc/html/rfc7235#section-3.1 which is why that's used at the resource. And the token endpoint uses 400 for most of its errors.

**Comment by panva** [comment]
Great, something worth calling out explicitly then.

**Comment by selfissued** [comment]
I'm willing to review the draft and ensure that it's explicit that token responses to be 400 but resource error responses to be 401.
