### ISSUE TITLE
add note about HTTP caching when returning DPoP-Nonce 

### ISSUE THREAD

**Issue by bc-pi** [danielfett/draft-dpop#95]
per https://mailarchive.ietf.org/arch/msg/oauth/DEmWIR1lY7q2AbaSXP6HguWlK5s/

**Comment by selfissued** [comment]
What should the note say?

**Comment by bc-pi** [comment]
I think only that responses that have a `DPoP-Nonce` header need to be uncacheable.

**Comment by b---c** [comment]
PR #97 merged 52506d648c514b7c697fee0f3c9a02647bf473d7
