### ISSUE TITLE
DPoP request to STS

### ISSUE THREAD

**Issue by asharif1990** [danielfett/draft-dpop#96]
I have a general question concerning the DPoP token request. Although in Section 5 of the draft, it is already mentioned that the DPoP token request can be applied to all token requests regardless of the grant type, I would like to double-check with you if in the same way it can be adopted for the STS token request (RFC8693) as well or further consideration should be applied?

**Comment by b---c** [comment]
The intent is that it can be used in general with RFC8693 to have issued tokens be bound without necessarily needing further consideration.

**Comment by asharif1990** [comment]
Okay, perfect. thanks for the clarification. I am going to close this issue.
